name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release Assets (YAML and README)
        run: |
          mkdir -p release_assets
          cp helios-display-esp8266.yaml release_assets/
          cp README.md release_assets/
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Automated release for ${{ github.ref_name }}.
            See CHANGELOG or commit history for details.
          files: |
            release_assets/helios-display-esp8266.yaml
            release_assets/README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
